<a href="https://colab.research.google.com/github/swopnimghimire-123123/Maths_For_ML/blob/main/Linear_Algebra_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Three-dimensional linear transformations

In [ ]:
import numpy as np

# original vector
v = np.array([1,2,3])

# 3d transformation matrix
A = np.array([[2,0,1],
              [-1,3,0],
              [0,0,1]])

# applied trasformation
v_transformed = A.dot(v) # v_transformed = A @ v
print("original vector:",v)
print("transformed vector:",v_transformed)

original vector: [1 2 3]
transformed vector: [5 5 3]


### Other Linear Transformations on Vectors

Besides scaling, rotation, shear, and reflection, there are several other transformations we can apply using matrices:

1. **Projection**  
   - Projects a vector onto a line, plane, or subspace.  
   - Example: projecting `[x, y, z]` onto the xy-plane sets z = 0.  
   - Matrix form:  
     ```
     [[1, 0, 0],
      [0, 1, 0],
      [0, 0, 0]]
     ```

2. **Permutation (Axis Swap)**  
   - Rearranges vector components.  
   - Example: swapping x and y in `[x, y, z]`.  
   - Matrix form:  
     ```
     [[0, 1, 0],
      [1, 0, 0],
      [0, 0, 1]]
     ```

3. **Orthogonal Transformation**  
   - Preserves lengths and angles (rotations + reflections).  
   - All orthogonal matrices have determinant = ±1.

4. **Identity Transformation**  
   - Leaves vectors unchanged.  
   - Matrix form: identity matrix `I`.

5. **Zero Transformation**  
   - Sends every vector to the zero vector.  
   - Matrix form: all entries are 0.

---


In [ ]:
import numpy as np

# original vector
v = np.array([2,3,4])
print("Original Vector:",v)

# 1. Projection onto xy plane
p = np.array([[1,0,0],
              [0,1,0],
              [0,0,0]])
v_projection = p.dot(v) # dot product and projection are the same thing
print("Projection onto xy plane:",v_projection)

# 2.permutation (swap x and y)
perm = np.array([[0,1,0],
                 [1,0,0],
                 [0,0,1]])
v_permuted = perm.dot(v)
print("Permuted Vector:",v_permuted)

# 3.orthogonal transformation (rotation around z axis 90 degree)
orth = np.array([[0,-1,0],
                 [1,0,0],
                 [0,0,1]])
v_orth = orth.dot(v)
print("Orthogonal Transformation:",v_orth)

# identity transformation
i = np.eye(3)
v_id = i @ v
print("Identity matrix:",v_id)

# zero transformation
z = np.zeros((3,3))
v_zero = z @ v
print("Zero matrix:",v_zero)


Original Vector: [2 3 4]
Projection onto xy plane: [2 3 0]
Permuted Vector: [3 2 4]
Orthogonal Transformation: [-3  2  4]
Identity matrix: [2. 3. 4.]
Zero matrix: [0. 0. 0.]


#  Determinant and Its Meaning in Linear Transformations

###  Definition
- The **determinant** of a square matrix measures how a **linear transformation** changes area (2D) or volume (3D).  
- For a 2×2 matrix:
\[
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}, \quad \det(A) = ad - bc
\]  
- For a 3×3 matrix:
\[
A = \begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \end{bmatrix}, \quad
\det(A) = a(ei - fh) - b(di - fg) + c(dh - eg)
\]

---

###  Geometric Meaning
1. **Scaling of area/volume**  
   - In 2D: \(|\det(A)|\) = factor by which the area of a shape is scaled.  
   - In 3D: \(|\det(A)|\) = factor by which volume is scaled.

2. **Orientation**
   - \(\det(A) > 0\) → preserves orientation (no flipping).  
   - \(\det(A) < 0\) → reverses orientation (flips space).

3. **Special Cases**
   - \(\det(A) = 0\) → transformation **collapses space**, e.g., a square becomes a line or a plane becomes a line; the matrix is **singular**.

---

###  Example
- Matrix: \(A = [[2, 1], [3, 4]]\)  
- Determinant: \(\det(A) = 2*4 - 3*1 = 5\)  
- Meaning: Any area in the plane is **scaled 5×** under this transformation.


In [ ]:
import numpy as np

# 2x2 matrix
A = np.array([[2, 1],
              [3, 4]])

det_A = np.linalg.det(A)
print("Matrix:\n", A)
print("Determinant:", det_A)

# taking a 3x3 matrix
B = np.array([[1, 2, 3],
              [0, 4, 5],
              [1, 0, 6]])

det_B = np.linalg.det(B)
print("\n3x3 Matrix:\n", B)
print("Determinant:", det_B)

Matrix:
 [[2 1]
 [3 4]]
Determinant: 5.000000000000001

3x3 Matrix:
 [[1 2 3]
 [0 4 5]
 [1 0 6]]
Determinant: 22.000000000000004


### `fun fact:`  det(M1M2) = det(M1) det(M2)