<a href="https://colab.research.google.com/github/swopnimghimire-123123/Maths_For_ML/blob/main/Linear_Algebra_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Cramer's Rule (Geometric Explanation)

###  Definition
- Cramer's Rule solves a system of **n linear equations with n unknowns**:
\[
A \mathbf{x} = \mathbf{b}, \quad A \text{ is square and det(A) ≠ 0}
\]

- Solution:
\[
x_i = \frac{\det(A_i)}{\det(A)}
\]
where \(A_i\) = matrix A with column i replaced by vector b.

---

###  Geometric Meaning
1. In 2D:
   - System:
\[
\begin{cases} a_1 x + b_1 y = c_1 \\ a_2 x + b_2 y = c_2 \end{cases}
\]
   - det(A) = area of parallelogram spanned by column vectors of A.  
   - det(A_i)/det(A) = ratio of areas → gives coordinate along x_i.

2. In 3D:
   - det(A) = volume of parallelepiped spanned by column vectors of A.  
   - det(A_i)/det(A) = ratio of volumes → gives coordinate along x_i.  

-  So **Cramer’s Rule** = computing each variable as a **scaled ratio of areas or volumes**, giving **exact coordinates** in space.

---


In [ ]:
import numpy as np

# system 2x + 3y = 7 ; 4x + 5y = 11
A = np.array([[2,3],
              [4,5]])
b = np.array([[7,11]])

# determinant of A
print("A\n",A)
det_A = np.linalg.det(A)
print(f"det(A) = {det_A}")

# determinant with first column replaced (for x)
A1 = A.copy()
A1[:,0] = b
print("A1\n",A1)
det_A1 = np.linalg.det(A1)
print(f"det(A1) = {det_A1}")

# determinant with second column replaced (for y)
A2 = A.copy()
A2[:,1] = b
print("A2\n",A2)
det_A2 = np.linalg.det(A2)
print(f"det(A2) = {det_A2}")

# solution using cramers rule
x = det_A1/det_A
y = det_A2/det_A

print("\n")
print("Determinant of A:", det_A)
print("Determinant replacing first column (x):", det_A1)
print("Determinant replacing second column (y):", det_A2)
print("Solution: x =", x, ", y =", y)


A
 [[2 3]
 [4 5]]
det(A) = -2.0
A1
 [[ 7  3]
 [11  5]]
det(A1) = 1.9999999999999984
A2
 [[ 2  7]
 [ 4 11]]
det(A2) = -6.0


Determinant of A: -2.0
Determinant replacing first column (x): 1.9999999999999984
Determinant replacing second column (y): -6.0
Solution: x = -0.9999999999999992 , y = 3.0


#  Gaussian Elimination (3x3 System)

- Solve the system A x = b using **row operations**.  
- Each step shows how the matrix is transformed into **upper triangular form**, then back-substitution gives the solution.


In [ ]:
import numpy as np

# define the system : 3x3 example
# Example system:
# 2x + 3y - z = 5
# 4x + y + 2z = 6
# -2x + 5y + 2z = 7

A = np.array([[2, 3, -1],
              [4, 1, 2],
              [-2, 5, 2]], dtype=float)
b = np.array([5, 6, 7], dtype=float)

# Augmented matrix
aug = np.hstack([A, b.reshape(-1,1)])
print("Augmented Matrix:\n",aug,"\n")

# Gaussian Elemination
n = 3
for i in range(n):
  # make the diagonal element 1 by dividing the row
  aug[i] = aug[i] / aug[i,i]
  print(f"Step {i+1} - Normalize row {i+1}:\n", aug, "\n")

Augmented Matrix:
 [[ 2.  3. -1.  5.]
 [ 4.  1.  2.  6.]
 [-2.  5.  2.  7.]] 

Step 1 - Normalize row 1:
 [[ 1.   1.5 -0.5  2.5]
 [ 4.   1.   2.   6. ]
 [-2.   5.   2.   7. ]] 

Step 2 - Normalize row 2:
 [[ 1.   1.5 -0.5  2.5]
 [ 4.   1.   2.   6. ]
 [-2.   5.   2.   7. ]] 

Step 3 - Normalize row 3:
 [[ 1.   1.5 -0.5  2.5]
 [ 4.   1.   2.   6. ]
 [-1.   2.5  1.   3.5]] 



In [ ]:
import numpy as np

# Define the system: 3x3 example
# Example system:
# 2x + 3y - z = 5
# 4x + y + 2z = 6
# -2x + 5y + 2z = 7

A = np.array([[2, 3, -1],
              [4, 1, 2],
              [-2, 5, 2]], dtype=float)
b = np.array([5, 6, 7], dtype=float)

# Augmented matrix
aug = np.hstack([A, b.reshape(-1,1)])
print("Initial Augmented Matrix:\n", aug, "\n")

# Gaussian Elimination
n = 3
for i in range(n):
    # Make the diagonal element 1 by dividing the row
    aug[i] = aug[i] / aug[i,i]
    print(f"Step {i+1} - Normalize row {i+1}:\n", aug, "\n")

    # Eliminate the entries below the pivot
    for j in range(i+1, n):
        factor = aug[j,i]
        aug[j] = aug[j] - factor * aug[i]
        print(f"Step {i+1}.{j} - Eliminate row {j+1}:\n", aug, "\n")

# Back-substitution with print statements
x = np.zeros(n)
for i in range(n-1, -1, -1):
    sum_ax = np.sum(aug[i,i+1:n]*x[i+1:n])
    x[i] = aug[i,-1] - sum_ax
    print(f"Back-substitution step for x[{i}] -> {x[i]} (augmented row: {aug[i]})")


print("Solution vector [x, y, z]:", x)


Initial Augmented Matrix:
 [[ 2.  3. -1.  5.]
 [ 4.  1.  2.  6.]
 [-2.  5.  2.  7.]] 

Step 1 - Normalize row 1:
 [[ 1.   1.5 -0.5  2.5]
 [ 4.   1.   2.   6. ]
 [-2.   5.   2.   7. ]] 

Step 1.1 - Eliminate row 2:
 [[ 1.   1.5 -0.5  2.5]
 [ 0.  -5.   4.  -4. ]
 [-2.   5.   2.   7. ]] 

Step 1.2 - Eliminate row 3:
 [[ 1.   1.5 -0.5  2.5]
 [ 0.  -5.   4.  -4. ]
 [ 0.   8.   1.  12. ]] 

Step 2 - Normalize row 2:
 [[ 1.   1.5 -0.5  2.5]
 [-0.   1.  -0.8  0.8]
 [ 0.   8.   1.  12. ]] 

Step 2.2 - Eliminate row 3:
 [[ 1.   1.5 -0.5  2.5]
 [-0.   1.  -0.8  0.8]
 [ 0.   0.   7.4  5.6]] 

Step 3 - Normalize row 3:
 [[ 1.          1.5        -0.5         2.5       ]
 [-0.          1.         -0.8         0.8       ]
 [ 0.          0.          1.          0.75675676]] 

Back-substitution step for x[2] -> 0.7567567567567567 (augmented row: [0.         0.         1.         0.75675676])
Back-substitution step for x[1] -> 1.4054054054054055 (augmented row: [-0.   1.  -0.8  0.8])
Back-substitution s

### Or you just just compute it using computer

In [ ]:
import numpy as np

# Define the system: A x = b
A = np.array([[2, 3, -1],
              [4, 1, 2],
              [-2, 5, 2]], dtype=float)
b = np.array([5, 6, 7], dtype=float)

# Solve directly
x = np.linalg.solve(A, b)

print("Solution vector [x, y, z]:", x)


Solution vector [x, y, z]: [0.77027027 1.40540541 0.75675676]
