<a href="https://colab.research.google.com/github/swopnimghimire-123123/Maths_For_ML/blob/main/Linear_Algebra_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Inverse matrices, column space, and null space

# 📌 Inverse Matrices

### 🔹 Definition
- The **inverse** of a square matrix \(A\) is a matrix \(A^{-1}\) such that:
\[
A \cdot A^{-1} = A^{-1} \cdot A = I
\]  
where \(I\) is the identity matrix.

- Only **non-singular matrices** (determinant ≠ 0) have inverses.

---

### 🔹 Formulas

**2D Matrix**
\[
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}, \quad
A^{-1} = \frac{1}{\det(A)} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
\]

**3D Matrix**
- More complex; typically computed using **cofactor matrix and determinant**:
\[
A^{-1} = \frac{1}{\det(A)} \text{Adj}(A)
\]

---

### 🔹 Physical Meaning
1. **Undoing a transformation**  
   - If \(A\) transforms vector \(v\) to \(v'\) (\(v' = A v\)),  
     then \(A^{-1}\) brings it back: \(v = A^{-1} v'\).

2. **Geometric Interpretation**
   - Scaling, rotation, reflection, shear → inverse applies the **opposite effect**.  
   - Example: a rotation of 90° clockwise → inverse rotates 90° counterclockwise.

3. **Important**
   - If \(\det(A) = 0\), there is **no inverse**, because the transformation collapses space (cannot undo it).

---


In [ ]:
import numpy as np

# 2D matrix example
A2 = np.array([[2, 1],
               [3, 4]])
A2_inv = np.linalg.inv(A2)
print("2D Matrix:\n", A2)
print("Inverse:\n", A2_inv)
print("Check A * A_inv:\n", A2 @ A2_inv)

# 3D matrix example
A3 = np.array([[1, 2, 3],
               [0, 4, 5],
               [1, 0, 6]])
A3_inv = np.linalg.inv(A3)
print("\n3D Matrix:\n", A3)
print("Inverse:\n", A3_inv)
print("Check A * A_inv:\n", A3 @ A3_inv)

2D Matrix:
 [[2 1]
 [3 4]]
Inverse:
 [[ 0.8 -0.2]
 [-0.6  0.4]]
Check A * A_inv:
 [[1. 0.]
 [0. 1.]]

3D Matrix:
 [[1 2 3]
 [0 4 5]
 [1 0 6]]
Inverse:
 [[ 1.09090909 -0.54545455 -0.09090909]
 [ 0.22727273  0.13636364 -0.22727273]
 [-0.18181818  0.09090909  0.18181818]]
Check A * A_inv:
 [[ 1.00000000e+00  2.77555756e-17  5.55111512e-17]
 [ 5.55111512e-17  1.00000000e+00 -5.55111512e-17]
 [-1.11022302e-16  5.55111512e-17  1.00000000e+00]]


# 📌 Column Space of a Matrix

### 🔹 Definition
- The **column space** of a matrix \(A\) is the set of all possible **linear combinations of its columns**.  
- Denoted as **Col(A)**.  
- If \(A\) is \(m \times n\) (m rows, n columns), the column space is a **subspace of ℝ^m**.

---

### 🔹 Physical Meaning
1. Each column of the matrix is a vector in **m-dimensional space**.  
2. The column space represents all the **vectors that can be reached** by linearly combining the columns.  
3. In terms of **linear transformation**:  
   - If \(A\) maps vectors from ℝ^n → ℝ^m, the column space is the set of all **possible outputs** of the transformation.

---

### 🔹 Example
Matrix:  
\[
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}
\]  
- Columns: \(c_1 = [1,3,5]^T, c_2 = [2,4,6]^T\)  
- Column space = all vectors of the form \(x c_1 + y c_2\) for scalars \(x, y\).

---



In [ ]:
import numpy as np
a = np.array([[1,2],
              [3,4],
              [5,6]])

# compute the rank to understand the dimension of column space
rank = np.linalg.matrix_rank(a)
print("Matrix a:\n",a)
print("Rank (dimension of column space):",rank)

# colum space = linear combination of columns
# for visualization, we can get the columns as vectors
c1 = a[:,0]
c2 = a[:,1]
print("Column 1:",c1)
print("Column 2:",c2)

# Example: a linear combination
x, y = 2, -1
v = x * c1 + y * c2
print(f"Example linear combination: 2*c1 - 1*c2 =", v)

Matrix a:
 [[1 2]
 [3 4]
 [5 6]]
Rank (dimension of column space): 2
Column 1: [1 3 5]
Column 2: [2 4 6]
Example linear combination: 2*c1 - 1*c2 = [0 2 4]


# 📌 Null Space of a Matrix

### 🔹 Definition
- The **null space** (or kernel) of a matrix \(A\) is the set of all vectors \(x\) such that:  
\[
A \cdot x = 0
\]  
- Denoted as **Null(A)**.  
- If \(A\) is \(m \times n\), the null space is a **subspace of ℝ^n**.

---

### 🔹 Physical Meaning
1. The null space contains all vectors that are **mapped to the zero vector** by the linear transformation \(A\).  
2. Geometrically: these are directions that get **collapsed** by the transformation.  
3. Dimension of null space = **n − rank(A)** (number of free variables).

---

### 🔹 Example
Matrix:  
\[
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
\]  
- Null space = all vectors \([x, y, z]^T\) satisfying:  
\[
1x + 2y + 3z = 0, \quad 4x + 5y + 6z = 0
\]  
- Any vector in null space is **sent to [0,0]^T**.



In [ ]:
import numpy as np
from scipy.linalg import null_space

a = np.array([[1,2,3],
              [4,5,6]])

# computer null space
N = null_space(a)
print("Matrix a:\n",a)
print("Null Space:\n",N)

print(N.shape)
# Any linear combination of these basis vectors is in null space
v = 2*N[:,0] - 3*N[:,1] if N.shape[1] > 1 else 3*N[:,0]
print("Example vector in null space:", v)

# Verification
print("A @ v =", a @ v)  # Should be (approximately) zero vector

Matrix a:
 [[1 2 3]
 [4 5 6]]
Null Space:
 [[ 0.40824829]
 [-0.81649658]
 [ 0.40824829]]
(3, 1)
Example vector in null space: [ 1.22474487 -2.44948974  1.22474487]
A @ v = [8.8817842e-16 0.0000000e+00]


# 📌 Nonsquare Matrices as Transformations Between Dimensions

### 🔹 Definition
- A **nonsquare matrix** has dimensions **m × n** where m ≠ n.  
- It represents a linear transformation:  
\[
A: \mathbb{R}^n \to \mathbb{R}^m
\]  
- Input vectors have **n components**, output vectors have **m components**.  

---

### 🔹 Physical Meaning
1. **Dimension change**
   - If m > n → transformation **expands to higher dimension** (embedding).  
   - If m < n → transformation **reduces to lower dimension** (projection).  

2. **Column space**
   - Columns of A live in ℝ^m.  
   - All possible outputs = **column space of A**.  

3. **Null space**
   - Vectors in ℝ^n mapped to 0 form the **null space**.  
   - Dimension = n − rank(A).  

4. **No standard inverse**
   - Only square, full-rank matrices have inverses.  
   - Nonsquare matrices can have **pseudoinverse** for solving `Ax = b`.

---

### 🔹 Example
Matrix \(A: \mathbb{R}^3 \to \mathbb{R}^2\):  
\[
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
\]  

- Input vector: \(v = [x, y, z]^T \in \mathbb{R}^3\)  
- Output vector: \(A v \in \mathbb{R}^2\)  

- Column space → plane in ℝ² spanned by `[1,4]` and `[2,5]`  
- Null space → line in ℝ³ along which input vectors get collapsed to 0.

---



In [ ]:
#  Example: Nonsquare Matrix Transformation
import numpy as np
from scipy.linalg import null_space

# 2x3 matrix (maps R^3 → R^2)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

v = np.array([1, 0, -1])  # example input vector in R^3
output = A @ v            # transformed vector in R^2

print("Matrix A:\n", A)
print("Input vector v:", v)
print("Output vector A @ v:", output)

# Null space (vectors in R^3 mapped to 0)
N = null_space(A)
print("Null space basis vectors:\n", N)

# Example linear combination in null space
if N.shape[1] > 0:
    v_null = 2*N[:,0]
    print("Example vector in null space:", v_null)
    print("Check A @ v_null:", A @ v_null)


Matrix A:
 [[1 2 3]
 [4 5 6]]
Input vector v: [ 1  0 -1]
Output vector A @ v: [-2 -2]
Null space basis vectors:
 [[ 0.40824829]
 [-0.81649658]
 [ 0.40824829]]
Example vector in null space: [ 0.81649658 -1.63299316  0.81649658]
Check A @ v_null: [4.4408921e-16 0.0000000e+00]
