<a href="https://colab.research.google.com/github/swopnimghimire-123123/Maths_For_ML/blob/main/Linear_Algebra_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Basis Vectors and Representation

The **i** and **j** vectors, representing one unit along the x-axis and y-axis respectively, are called **basis vectors**.  

You can think of the vector `[2, 3]` as:  
- 2 times the **i** vector  
- 3 times the **j** vector  

**Vector:** [2, 3]  

**Becomes:** 2i + 3j


# Change in basis

#  Change of Basis – Theory

###  What is a Basis?
- A **basis** is a set of linearly independent vectors that span a vector space.  
- In 2D, the standard basis is:
  - **i = [1,0]**
  - **j = [0,1]**
- Any vector (e.g., [2,3]) can be written as:
  \[
  [2,3] = 2i + 3j
  \]

---

###  Change of Basis
- The **same vector** can have **different coordinates** if we choose a different basis.  
- Example:  
  Suppose the new basis is:
  \[
  b_1 = [1,1], \quad b_2 = [1,-1]
  \]
  Then the vector [2,3] can be expressed as a combination of \(b_1\) and \(b_2\).

- This does **not** change the vector itself (its position in space stays the same),  
  only the **numbers used to describe it**.

---

###  Why Important?
1. **PCA (Principal Component Analysis):** Data is expressed in a new basis aligned with directions of maximum variance.  
2. **Fourier Transform:** A change of basis from time-domain to frequency-domain.  
3. **Simplification:** In the right basis, matrices become diagonal (easier math).  
4. **Machine Learning:** Embeddings (e.g., word vectors) are alternative bases for representing data.

---

 **In short:**  
A **change of basis** is like changing your "coordinate system."  
The vector itself stays the same, but its coordinates (the way we describe it) change.


In [ ]:
import numpy as np

# Original vector in standard basis
v = np.array([2, 3])
print("Original vector (standard basis):", v)

# Define a new basis (must be linearly independent)
b1 = np.array([1, 1])
b2 = np.array([1, -1])
B = np.column_stack((b1, b2))  # Basis matrix

print("New basis vectors:\n", B)

# Step 1: Find coordinates of v in new basis
# Solve B * coords = v
coords = np.linalg.solve(B,v)
print("Coordinates of v in new basis:", coords)

# Step 2: Reconstruct v back from new basis
v_reconstruct = B @ coords
print("Reconstructed vector:", v_reconstruct)

Original vector (standard basis): [2 3]
New basis vectors:
 [[ 1  1]
 [ 1 -1]]
Coordinates of v in new basis: [ 2.5 -0.5]
Reconstructed vector: [2. 3.]


#  Linear Combinations – Theory

###  Definition
- A **linear combination** of vectors is a sum of those vectors multiplied by scalars (numbers).  


---

###  Examples
1. Let \(v_1 = [1,0]\), \(v_2 = [0,1]\) (standard basis in 2D).  
   A vector \([2,3]\) can be written as:
   \[
   [2,3] = 2 \cdot v_1 + 3 \cdot v_2
   \]

2. In 3D, if \(v_1=[1,0,0], v_2=[0,1,0], v_3=[0,0,1]\), then
\[
[2,3,4] = 2v_1 + 3v_2 + 4v_3
\]

---

###  Importance
- Linear combinations are the **building blocks of vector spaces**.  
- They help determine:
  1. **Span** – the set of all possible linear combinations of given vectors.  
  2. **Basis** – minimal set of vectors whose linear combinations can describe all vectors in the space.  
- In **ML**, data points, feature vectors, and transformations often use linear combinations.

---

 **In short:**  
A linear combination = multiplying vectors by numbers (scalars) and adding them together to make a new vector.


In [ ]:
# linear combination
import numpy as np

# defining vectors
v1 = np.array([1,0])
v2 = np.array([0,1])

# scalers
c1 = 2
c2 = 3

# linear combination
result = c1*v1 + c2*v2
print("Linear combination of 2-d basis vector:",result)

# another example in 3 dimensions
v3 = np.array([1,0,0])
v4 = np.array([0,1,0])
v5 = np.array([0,0,1])

c3 = 2
c4 = 3
c5 = 4

result2 = c3*v3 + c4*v4 + c5*v5
print("Linear combination of 3-d basis vector:",result2)

Linear combination of 2-d basis vector: [2 3]
Linear combination of 3-d basis vector: [2 3 4]


#  Span – Theory

###  Definition
- The **span** of a set of vectors is the set of **all possible linear combinations** of those vectors.  

---

###  Examples
1. 2D example:  
   - Vectors: \(v_1=[1,0], v_2=[0,1]\)  
   - Span\(\{v_1,v_2\}\) = **all vectors in 2D space** because any vector \([x,y]\) can be written as a linear combination of \(v_1\) and \(v_2\).

2. Single vector:  
   - Vector: \(v=[1,2]\)  
   - Span\(\{v\}\) = **all vectors on the line through the origin in the direction of \(v\)**.

---

###  Importance
- **Span determines the "reach" of vectors**: how much of the space they can cover via linear combinations.  
- Related concepts:  
  1. **Linear Independence** – if vectors are independent, their span is “maximal” in that space.  
  2. **Basis** – a minimal set of vectors whose span is the entire space.  
- In **ML**, span relates to feature representation and the dimension of the space your data occupies.

---

 **In short:**  
The set of all possible vectors you can reach with linear combinations of a given pair of vectors is called the "span" of those two vectors.


In [ ]:
import numpy as np

# define a 2d vector
v1 = np.array([1,0])
v2 = np.array([0,1])

print("vectors in the span:")
# example linear combination of the span
print( 2*v1 + v2 )
print( 3*v1 + v2 )
print( 0.5*v1 + 0.75*v2 )

print("\nsome more examples of span:")
# Another example: span of a single vector
v = np.array([1, 2])
scalars = [-2, -1, 0, 1, 2, 5, 4, 3, 2, 1, 5, 7, 0]
span_vectors = [i*v for i in scalars]
print("Span of [1,2]:", span_vectors)

vectors in the span:
[2 1]
[3 1]
[0.5  0.75]

some more examples of span:
Span of [1,2]: [array([-2, -4]), array([-1, -2]), array([0, 0]), array([1, 2]), array([2, 4]), array([ 5, 10]), array([4, 8]), array([3, 6]), array([2, 4]), array([1, 2]), array([ 5, 10]), array([ 7, 14]), array([0, 0])]


### Visualizing Collections of Vectors

It gets very crowded to think about a whole collection of vectors sitting on a line, and even more crowded to think about all two-dimensional vectors at once, filling up the plane.  

So, when dealing with collections of vectors like this, it is common to represent each one **just with a point in space**—the point at the **tip of the vector**.


#  Linear Independence and Dependence – Theory

###  Linear Independence
- A set of vectors \(\{v_1, v_2, \dots, v_n\}\) is **linearly independent** if **no vector in the set can be written as a linear combination of the others**.  
- Mathematically:
\[
c_1v_1 + c_2v_2 + \dots + c_nv_n = 0 \implies c_1 = c_2 = \dots = c_n = 0
\]  
- Example in 2D: \(v_1 = [1,0], v_2 = [0,1]\) → independent, because neither vector can be made from the other.

---

###  Linear Dependence
- A set of vectors is **linearly dependent** if **at least one vector can be written as a combination of the others**.  
- Example in 2D: \(v_1=[1,0], v_2=[2,0]\) → dependent, because \(v_2 = 2 \cdot v_1\).

---

###  Importance
1. **Basis** – only linearly independent vectors can form a basis.  
2. **Span** – dependent vectors do not add new dimensions to the span.  
3. **ML / DS** – redundancy in features (multicollinearity) is a case of linear dependence.

---

 **In short:**  
- **Independent:** No vector is redundant.  
- **Dependent:** Some vector(s) can be made from others.


In [ ]:
#  Linear Independence / Dependence – Python Example
import numpy as np

# Linearly independent vectors in 2D
v1 = np.array([1,0])
v2 = np.array([0,1])

# Check determinant of matrix formed by stacking vectors
matrix_indep = np.column_stack((v1,v2))
det = np.linalg.det(matrix_indep)
print("Determinant (independent check):", det)
# Non-zero determinant is independent

# linearly dependent vectors
v3 = np.array([1,2])
v4 = np.array([2,4])

matrix_dep = np.column_stack((v3,v4))
det = np.linalg.det(matrix_dep)
print("Determinant (dependent check):", det)
# zero determinant matirx is dependent

# we can also use if else to simply get the result of dependency

Determinant (independent check): 1.0
Determinant (dependent check): 0.0


#  Span in 3D – Theory

###  Definition
- The **span** of a set of 3D vectors is the set of **all possible linear combinations** of those vectors.  
- If you have vectors \(v_1, v_2, v_3\), the span is:
\[
\text{Span}\{v_1, v_2, v_3\} = \{c_1v_1 + c_2v_2 + c_3v_3 \mid c_1, c_2, c_3 \in \mathbb{R}\}
\]

---

###  Examples
1. Three vectors in 3D:  
   \[
   v_1=[1,0,0], \quad v_2=[0,1,0], \quad v_3=[0,0,1]
   \]  
   - Span\(\{v_1,v_2,v_3\}\) = **all vectors in 3D space** (the entire 3D space).

2. Two vectors in 3D:  
   \[
   v_1=[1,0,0], \quad v_2=[0,1,0]
   \]  
   - Span\(\{v_1,v_2\}\) = **all vectors in the XY-plane** (a 2D plane in 3D space).

3. Single vector in 3D:  
   - Span\(\{v_1\}\) = **all vectors along the line in the direction of \(v_1\)**.

---

###  Importance
- Determines how much of the 3D space the vectors “cover.”  
- Related to **linear independence** and **basis**.  
- In **ML / Data Science**, understanding the span helps identify the **dimension of the data** and redundancy in features.

---

 **In short:**  
The span of 3D vectors = all vectors you can make using **any combination of those vectors**, forming lines, planes, or the whole 3D space.


In [ ]:
""" it's not just limited to these set of vectors as span is the
 collection of all the vectors within the space that can be reached by
 some sort of linear combination """

import numpy as np

v1 = np.array([1,0,0])
v2 = np.array([0,1,0])
v3 = np.array([0,0,1])

scaler = [11,2,3,4,5,6,6,7,7,8,99,10]
print("some examples of all the span vectors that lie in the 3d space")
for i in scaler:
  print(v1*i)
  print(v2*i)
  print(v3*i)


some examples of all the span vectors that lie in the 3d space
[11  0  0]
[ 0 11  0]
[ 0  0 11]
[2 0 0]
[0 2 0]
[0 0 2]
[3 0 0]
[0 3 0]
[0 0 3]
[4 0 0]
[0 4 0]
[0 0 4]
[5 0 0]
[0 5 0]
[0 0 5]
[6 0 0]
[0 6 0]
[0 0 6]
[6 0 0]
[0 6 0]
[0 0 6]
[7 0 0]
[0 7 0]
[0 0 7]
[7 0 0]
[0 7 0]
[0 0 7]
[8 0 0]
[0 8 0]
[0 0 8]
[99  0  0]
[ 0 99  0]
[ 0  0 99]
[10  0  0]
[ 0 10  0]
[ 0  0 10]


#  Problem Statement

Solve for scalars a and b in the vector equation: a*[2,3] + b*[-3,2] = [7,4].

what are the two scalers for a and b which form the vector [7,4] if we have the coordinates of the vectors as v=[2,3] and w=[-3,2] for an vector expression a*v + b*w.

In [ ]:
import numpy as np

# define the coordinate of the vectors
coordinate = np.array([[2,-3],
              [3,2]])

# define the result vector
result = np.array([7,4])

# solve for a and b
solution = np.linalg.solve(coordinate, result)

# print the solution
print("Solution:",solution)

Solution: [ 2. -1.]
