<a href="https://colab.research.google.com/github/swopnimghimire-123123/Maths_For_ML/blob/main/Linear_Algebra_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Change of Basis

###  Idea
- A vector can be represented in **different coordinate systems (bases)**.  
- Standard basis in 2D: i = [1,0], j = [0,1].  
- Another basis B = {b1, b2} can be any two linearly independent vectors.  
- Change of basis = represent vector v in terms of **new basis B**.

---

###  Formula
- Let P = [b1 b2] (matrix with new basis vectors as columns).  
- If v_old = coordinates in standard basis, then  
\[
v_{new} = P^{-1} v_{old}
\]  
- Conversely, to go back:  
\[
v_{old} = P v_{new}
\]

###  Geometric Meaning
- We are **re-expressing the same vector along new directions**.  
- Coordinates change, vector itself does not.


In [ ]:
import numpy as np

# original vector in standard basis
v = np.array([5,4])

# new basis vector
b1 = np.array([3,2])
b2 = np.array([1,1])

# basis matrix
basis = np.column_stack((b1,b2))

# coordinate of v in new basis
v_new = np.linalg.inv(basis) @ v
print("Vector v in standard basis :",v)
print("Vector v in new basis B:",v_new)

# converting the new vector again into the standard basis
v_old = basis @ v_new
print("Vector v in old basis :",v_old)

Vector v in standard basis : [5 4]
Vector v in new basis B: [1. 2.]
Vector v in old basis : [5. 4.]


#  Change of Basis in 3D

###  Idea
- A vector v in ℝ³ can be expressed in different bases.  
- Standard basis: i = [1,0,0], j = [0,1,0], k = [0,0,1]  
- New basis B = {b1, b2, b3}, where b1, b2, b3 are linearly independent vectors.  
- Change of basis = represent v in **new basis B**.

---

###  Formula
- Basis matrix: P = [b1 b2 b3] (columns are new basis vectors).  
- Coordinates in new basis:  
\[
v_{new} = P^{-1} v_{old}
\]  
- Convert back to standard basis:  
\[
v_{old} = P v_{new}
\]

###  Geometric Meaning
- Vector itself **does not change**, only its **coordinates along new directions** change.


In [ ]:
import numpy as np

# original vector in standar basis
v = np.array([4,5,6])
print("Original Vector:\n",v,"\n")

# new basis vectors
b1 = np.array([3,2,1])
b2 = np.array([1,1,0])
b3 = np.array([5,6,7])
basis = np.column_stack((b1,b2,b3))
print("New basis:\n",basis,"\n")

# coordinate in new basis
v_new = np.linalg.inv(basis) @ v
print("Vector in new basis:\n",v_new,"\n")

# convert back to standard basis
v_old = basis @ v_new
print("Vector in old basis:\n",v_old)

Original Vector:
 [4 5 6] 

New basis:
 [[3 1 5]
 [2 1 6]
 [1 0 7]] 

Vector in new basis:
 [-1.2500000e-01  8.8817842e-16  8.7500000e-01] 

Vector in old basis:
 [4. 5. 6.]


#  Change of Basis – Story Version

Imagine you are an explorer in a 3D world. You have your usual **map directions**: North (x-axis), East (y-axis), and Up (z-axis). This is your **standard basis**.  

Now, you find a **new local map** that uses directions based on landmarks:  
- b1 = direction to the mountain  
- b2 = direction to the river  
- b3 = direction to the tree  

These are your **new basis vectors**.  

You have a treasure at a point v = [4, 3, 5] in your original map (standard basis).  
- To explain the treasure’s location using the **local map directions**, you compute **coordinates along b1, b2, b3**.  
- This is exactly what **Change of Basis** does: it tells you **how far along each new landmark direction you need to go** to reach the same treasure.  

Mathematically:  
- Put your landmarks as columns in a matrix P = [b1 b2 b3].  
- Coordinates in new map (basis B): v_new = P⁻¹ · v.  
- To go back to standard map: v = P · v_new.  

 **Key Idea**: The treasure (vector) doesn’t move. Only the **way you describe it** changes depending on your reference directions.


In [ ]:
# Story example in python
import numpy as np

# Tresure location in standard map
v = np.array([4,3,5])
print("Original Vector :",v)
# New landmark directions (basis)
b1 = np.array([1, 0, 1])
b2 = np.array([0, 2, 1])
b3 = np.array([1, -1, 1])

p = np.column_stack((b1,b2,b3))

# coordinates of treasure in new map
v_new = np.linalg.inv(p) @ v
print("Tresure coordinates in new basis:",v_new)

# Back to standard map
v_old = p @ v_new
print("Tresure coordinates in old basis:",v_old)

Original Vector : [4 3 5]
Tresure coordinates in new basis: [ 5.  1. -1.]
Tresure coordinates in old basis: [4. 3. 5.]


#  Extra Insights on Change of Basis

1. **Vectors themselves don’t change**  
   - Only their **coordinates** change depending on which basis you use.  
   - Geometrically, the vector “stays in the same place in space,” but its description changes.

2. **Basis must be linearly independent**  
   - If the basis vectors are not independent, the inverse P⁻¹ does not exist, and you cannot compute the new coordinates.

3. **Change of basis + Linear Transformation**  
   - If you have a transformation T (matrix) in the standard basis and you switch to a new basis B:  
     \[
     [T]_B = P^{-1} \, T \, P
     \]  
     - This gives the **matrix of T in the new basis**.  
     - Useful in diagonalization, rotations, or simplifying computations.

4. **Intuition in physics / graphics**  
   - Change of basis = “looking at the same vector from a different set of axes.”  
   - Common in computer graphics (object vs world coordinates) and physics (local vs global frames).

5. **Shortcut for simple 2D / 3D cases**  
   - For small systems, sometimes you can **solve directly using linear combination of basis vectors** without computing P⁻¹ explicitly.

6. **Story reinforcement**  
   - Standard map = your usual coordinate system.  
   - New map = new landmarks / directions.  
   - Treasure = the vector.  
   - Coordinates change → how far to go along each new landmark.  

**Summary**: Change of basis = **re-describing vectors in terms of new reference directions**, keeping the vector itself fixed in space.
